Improvement: get token price
velocitylabs-org/turtle pull request #191
Opened 2024-11-21 16:38 UTC by Victor-Salomon

Implement cached token price fetch in: 

- useFees
- useSnowbridgeApi
- useParaspellApi

And support allowanceLoading checks before displaying the TxSummy component to avoid overlaps. 

Every call to goingecko API is now cached globally.

2024-11-21 19:53 UTC, NunoAlexandre reviewed
Nice stuff :) just a few comments

2024-11-21 19:53 UTC, NunoAlexandre commented on app/src/components/Transfer.tsx
> +      {tokenAmount &&
Let's create a const "shouldDisplayTxSummary" to clean this up here

2024-11-21 19:53 UTC, NunoAlexandre commented on app/src/components/TxSummary.tsx
> +  const { price, loading: isTokenPriceLoading } = useTokenPrice(tokenAmount.token)
A more natural semantic here would be "isLoadingTokenPrice"

2024-11-21 19:53 UTC, NunoAlexandre commented on app/src/hooks/useFees.tsx
> +          const polkadot = REGISTRY[env].tokens.find(t => t.name === 'Polkadot')
Let's not do this. We are adding a dependency and a O(n) lookup on the registry that filters on a hardcoded value just to pass the coingeko Id for DOT which we statically know to be "polkadot" so let's just pass that directly instead as it was. A compromise is to reference 'mainnet.Polkadot.DOT'.

2024-11-21 19:53 UTC, NunoAlexandre commented on app/src/hooks/useFees.tsx
> +          const ethereum = REGISTRY[env].tokens.find(t => t.name === 'Ethereum')
Same here about Ethereum

2024-11-21 19:53 UTC, NunoAlexandre commented on app/src/registry/mainnet.ts
>      Eth.WETH,
We should remove this. I understand you needed to add it to filter the registry to find it and get the coingeko Id but read my comment above about undoing that for ETH and DOT 🙏

2024-11-22 07:55 UTC, Victor-Salomon commented on app/src/hooks/useFees.tsx
> +          const polkadot = REGISTRY[env].tokens.find(t => t.name === 'Polkadot')
@NunoAlexandre Al right! 
Since, `getCachedTokenPrice()` expects a `token:Token` as param, and not the `tokenId:string`, what do you think about this? 

=> `tokenUSDValue = (await getCachedTokenPrice(Eth.ETH))?.usd ?? 0`
=> `tokenUSDValue = (await getCachedTokenPrice(Polkadot.DOT))?.usd ?? 0`

It still relies on the registry but directly on the token itself, no more lookup, and we can still update according to the `env` (mainnet/testnet) later. 

Otherwise, I need refactoring both the API handler and the API itself directly.

2024-11-22 09:17 UTC, NunoAlexandre commented on app/src/hooks/useFees.tsx
> +          const polkadot = REGISTRY[env].tokens.find(t => t.name === 'Polkadot')
That's good, that's what I meant by the "compromise" option 👍  Let's go :)

2024-11-22 10:05 UTC, noahjoeris commented on app/src/components/Transfer.tsx
> +      {tokenAmount &&
100% agree

2024-11-22 10:07 UTC, noahjoeris commented on app/src/registry/mainnet.ts
>      Eth.WETH,
agree

2024-11-22 10:08 UTC, noahjoeris requested changes
What nuno said

2024-11-22 10:32 UTC, NunoAlexandre approved these changes
![image](https://github.com/user-attachments/assets/f7d43da7-610d-450f-b373-5477d69c8dfe)

2024-11-22 10:58 UTC, noahjoeris approved these changes

2024-11-22 11:07 UTC, merged