improvement: ocelloids tracking migration
velocitylabs-org/turtle pull request #240
Opened 2024-12-18 15:21 UTC by Victor-Salomon

2024-12-20 16:24 UTC, noahjoeris commented
It's sooo smooth 😍

2024-12-23 08:35 UTC, NunoAlexandre commented on app/src/hooks/useOngoingTransferCleaner.tsx
> +          message: 'Transfer verification failed.',
The language here is not quite there. There is no "verification" taking place here, it's just tracking. And personally I prefer to not end these small and single lines with a `.`

```suggestion
          message: 'Transfer tracking failed',
```

2024-12-23 08:35 UTC, NunoAlexandre commented
@Victor-Salomon what's the status of this PR? what's keeping it from being ready for review? :)

2024-12-23 09:00 UTC, Victor-Salomon commented
@NunoAlexandre, I need to discuss it a bit with you, I also need to discuss some points with the team.

2025-01-03 17:08 UTC, noahjoeris requested changes
Awesome job @Victor-Salomon. That was heavy work. Thanks. Left some suggestions. 🚀

2025-01-03 17:08 UTC, noahjoeris commented on app/src/hooks/useParaspellApi.tsx
> +                onchainTimestamp: new Date(),
Can we do that? To call it `onchain timestamp` but take the timestamp locally?

2025-01-03 17:08 UTC, noahjoeris commented on app/src/utils/ocelloids.ts
> +                break
sentry log

2025-01-06 14:49 UTC, NunoAlexandre reviewed
Looks good overall. It would be nice to thrive for cleaner code but this is a solid start of this migration. I left a few comments, Noah's review as good already 👍

2025-01-06 14:49 UTC, NunoAlexandre commented on app/src/utils/ocelloids.ts
> +const apiKey = process.env.NEXT_PUBLIC_OC_API_KEY_READ_WRITE || ''
do we handle whether the keys is well loaded? We must report that case

2025-01-06 14:49 UTC, NunoAlexandre commented on app/src/utils/transfer.ts
> +export const parachainsOnly = (
```suggestion
export const betweenParachains = (
```

or `isParaToPara`

2025-01-06 14:49 UTC, NunoAlexandre commented on app/src/utils/ocelloids.ts
> +export const xcmOcceloidsSubscribe = async (
Can you document this?

2025-01-06 15:10 UTC, Victor-Salomon commented on app/src/hooks/useOcelloidsSubscribe.tsx
> +  const { addCompletedTransfer } = useCompletedTransfers()
Let's not handle those naming inconsistencies in this PR as it's not in the scope, and the PR is already heavy.

2025-01-07 09:40 UTC, Victor-Salomon commented on app/src/hooks/useParaspellApi.tsx
> +                onchainTimestamp: new Date(),
I understand your comment. This key corresponds to the moment the transfer is finalized on the chain. (We do not have access to this data (date/timestamp) in the callback and it would be overkill to connect to the chain just for this). 

Any preference below?
  
- finalizedTimeStamp?
- finalizedAt?
- finalizedTxDate?
- finalizedDate?

2025-01-07 10:15 UTC, Victor-Salomon commented on app/src/utils/ocelloids.ts
> +const apiKey = process.env.NEXT_PUBLIC_OC_API_KEY_READ_WRITE || ''
Now we do :)

2025-01-07 10:34 UTC, Victor-Salomon commented on app/src/utils/ocelloids.ts
> +export const xcmOcceloidsSubscribe = async (
Done

2025-01-07 14:01 UTC, NunoAlexandre commented on app/src/hooks/useParaspellApi.tsx
> +                onchainTimestamp: new Date(),
> finalizedAt?

my vote ✋

2025-01-10 09:55 UTC, noahjoeris commented on app/src/utils/transfer.ts
> +  chain.chainId !== AssetHub.chainId && chain.chainId !== RelayChain.chainId
hmm I'm not sure. Maybe just add in the comments that it is incomplete.

2025-01-10 15:19 UTC, NunoAlexandre approved these changes
Nice :) a small step for humanity, a great step for Turtle 🐢

2025-01-11 13:55 UTC, noahjoeris approved these changes

2025-01-14 10:43 UTC, NunoAlexandre commented on app/src/utils/ocelloids.ts
> +                    : undefined
@Victor-Salomon we already know from `case xcm.XcmNotificationType.Hop` that this is a `Hop`, so why check it here again?

Another wide comment is to not use ternary operators on enums. `XcmNotificationType` is not a boolean so using ternary operators against it might lead to silent bugs

2025-01-14 10:52 UTC, NunoAlexandre approved these changes
Looks good to me apart from the comment about the ternary operator :) Happy to merge this and work on that later 👍

2025-01-14 10:53 UTC, Victor-Salomon commented on app/src/utils/ocelloids.ts
> +                    : undefined
well spotted, I've updated it several times and forgot to remove it :)
Thanks!

2025-01-14 10:59 UTC, noahjoeris commented on app/src/utils/transfer.ts
> + * ⚠️ the helper does not verify every system chain.
nice warning 😎

2025-01-14 11:02 UTC, noahjoeris commented on app/src/utils/ocelloids.ts
> +  if (!OCELLOIDS_API_KEY || !OCELLOIDS_API_KEY.length)
```suggestion
  if (!OCELLOIDS_API_KEY)
```
an empty string is false

2025-01-14 11:05 UTC, noahjoeris commented on app/src/utils/ocelloids.ts
> +                    : undefined
here as well

2025-01-14 11:08 UTC, noahjoeris commented on app/src/utils/ocelloids.ts
> +}
great

2025-01-14 11:08 UTC, noahjoeris approved these changes
amaaaaazing ❤️

2025-01-14 13:20 UTC, Victor-Salomon commented on app/src/utils/ocelloids.ts
> +                    : undefined
This is different: `outcome` needs to be narrowed down to `payload.destination`, which has 2 types possible.
If I remove the `undefined` return, the type will be `false | 'Success' | 'Fail'`.
Better like this since I handle `undefined` cases later.

2025-01-14 13:40 UTC, merged