Integration/landing page
velocitylabs-org/turtle pull request #25
Opened 2024-06-14 09:37 UTC by Victor-Salomon

This PR contains the landing page integration. 

It is still subject to minor adjustments I will conduct alongside of working on other tasks: 
- design updates
- animation
- texts/wording
- integration performances (compressing images(...))
- adjust configs according to the app (switch from daisy ui to shadcn, (...)) 
- sentry/vercel analytics

2024-06-14 10:30 UTC, noahjoeris approved these changes
LGTM!! ❤️

2024-06-14 18:37 UTC, NunoAlexandre commented
@Victor-Salomon I will give it a good review on Monday 🙏

2024-06-17 08:01 UTC, NunoAlexandre requested changes
Awesome to see this coming together 🏄  very cool!

I left some remarks but the high level feedback is that we still have some work to do before merging this.

This is how the page of this PR currently looks on my monitor:

<img width="1800" alt="Screenshot 2024-06-17 at 09 54 26" src="https://github.com/velocitylabs-org/turtle/assets/7075260/44c59bfc-8580-427a-8a9a-137f9685aa2c">

And this is how the designed page looks like:
<img width="1800" alt="Screenshot 2024-06-17 at 09 51 28" src="https://github.com/velocitylabs-org/turtle/assets/7075260/2a220c46-41e5-42b6-933d-4ee446682c90">

It's a huge difference coming from mostly details:

- The font is not set to the right one
- The sizes of buttons and font doesn't look similar to the design
- The top bar is different from what's designed - it's not designed to be sticky neither to have opacity and it has a different position and sizing as well
- The position of the features and the size of the visuals is also off
- We should work on the copywriting internally. It's fine if the tetx is not final but we shouldn't be using ecosystems and tokens that are not from the ecosystem and use cases we are working towards


That's it for now 🙏

2024-06-17 18:53 UTC, Victor-Salomon commented on site/public/chains.png
I've requested them to Brandon but he can only send png.
I will compress them and keep them..

2024-06-17 18:56 UTC, Victor-Salomon commented on site/src/components/assets/base-icons.tsx
> +        fill="#001B04"
We can. 
Using this method, you get your SVG organized by category and need to provide **a name** to use the corresponding one from the list: 
`<BaseIcon name="arrowRight" className="h-3" />`

But I will switch to a separate file

2024-06-17 19:00 UTC, Victor-Salomon commented on site/src/components/features.tsx
> +    <div className="relative z-30 -mt-28 md:-mt-40 lg:px-10">
Unfortunately, because of the wave background overlap between the sections (hero section/feature section), we can't set it with flex and force us to manage breakpoints manually.

2024-06-17 19:02 UTC, Victor-Salomon commented on site/src/components/tokens.tsx
> +export const TokenExchange = () => {
Sure, if it's good for you I will wait for the final design of the hero section and move on to the history/completed tx first, before going back to animations.

2024-06-17 19:03 UTC, Victor-Salomon commented on site/src/components/tokens.tsx
> +                //   icons dimentions downloaded from figma do not fit. This need to be addressed once we will get the final design and tokens.
I will remove this commit anyway

2024-06-17 19:04 UTC, Victor-Salomon commented on site/tailwind.config.ts
> +        sans: ['Inter', 'sans-serif'],
👌 Old comment from the initial setup. I will delete it as the font is implemented.

2024-06-18 07:38 UTC, NunoAlexandre commented on site/src/components/features.tsx
> +    <div className="relative z-30 -mt-28 md:-mt-40 lg:px-10">
hm but how does the background relate to the features container?

2024-06-18 07:38 UTC, NunoAlexandre commented on site/src/components/tokens.tsx
> +export const TokenExchange = () => {
Sure 👍

2024-06-18 07:52 UTC, NunoAlexandre approved these changes
Awesome 🔥

2024-06-18 08:05 UTC, Victor-Salomon commented on site/src/components/features.tsx
> +    <div className="relative z-30 -mt-28 md:-mt-40 lg:px-10">
The wave backgrounds are SVGs, in absolute position within a relatively positioned parent, similar to the token transfer component or the ellipse/ball animated. These backgrounds are not square but are full-width wave forms that overlap with other content, requiring manual adjustment. Flexbox does not provide a way to overlap content but provides a layout for items.

2024-06-19 07:33 UTC, merged