feat: Lookup ENS name for the connected wallet
velocitylabs-org/turtle pull request #42
Opened 2024-07-03 13:12 UTC by NunoAlexandre

Happy to receive suggestions for a different name rather than "display" 👀 

## To Do
- [ ] Support the name lookup for Polkadot addresses

2024-07-04 13:38 UTC, noahjoeris requested changes
🔥 🔥 🔥

2024-07-04 13:38 UTC, noahjoeris commented on app/src/components/completed/TransactionDialog.tsx
>    })
Can you use a hook? Would cleanup a lot and remove redundancy :)
```typescript
import { Network } from '@/models/chain'
import { lookupName } from '@/utils/transfer'
import { useCallback, useEffect, useState } from 'react'

const useLookupName = (network: Network, address: string) => {
  const [display, setDisplay] = useState<string | null>()

  const fetchName = useCallback(async () => {
    try {
      const name = await lookupName(network, address)
      setDisplay(name)
    } catch (e) {
      console.error(e)
    }
  }, [network, address])

  useEffect(() => {
    fetchName()
  }, [network, address])

  return display
}

export default useLookupName

2024-07-04 13:38 UTC, noahjoeris commented on app/src/utils/transfer.ts
> +}
Can we move error handling to the hook `useLookupName`?
```suggestion
export async function lookupName(network: Network, address: string): Promise<string | null> {
  switch (network) {
    case Network.Ethereum: {
      const provider = new ethers.CloudflareProvider()
      return provider.lookupAddress(address)
    }
    case Network.Polkadot: {
      //todo(nuno)
      return null
    }
  }
}
```

2024-07-08 08:31 UTC, NunoAlexandre commented on app/src/components/completed/TransactionDialog.tsx
>    })
Yeah you are right :) thanks, will do!

2024-07-08 14:37 UTC, Victor-Salomon approved these changes

2024-07-08 14:41 UTC, merged