feat: Prompt for ERC-20 spend approval
velocitylabs-org/turtle pull request #80
Opened 2024-08-07 19:18 UTC by NunoAlexandre

When the user is transferring a token from Ethereum, we now check whether they need to first sign the ERC-20 spend approval and show a nice call to action component so that the user does that before being able to submit the transfer.

<img width="520" alt="Screenshot 2024-08-07 at 21 16 17" src="https://github.com/user-attachments/assets/a8d8ad9c-0a75-4e6f-bddf-3ab3ebdb6b34">

### Caveats

- When the user signs the approval, we wait 10s to re-fetch the allowance but sometimes that's not enough so the `TokenSpendApproval` keeps on showing and only a change in the amount or other transfer input field triggers the fix.

2024-08-07 19:21 UTC, NunoAlexandre commented on app/src/components/Transfer.tsx
> +    erc20SpendAllowance !== undefined && erc20SpendAllowance < tokenAmount!.amount!
The logic is here that if `erc20SpendAllowance` is set and if it's below the amount, then it's required to be approved. We know here that `tokenAmount` is set because `erc20SpendAllowance` can not be set without a defined tokenAmount beforehand.

Happy to think of a more explicit and idiomatic approach but logically there's no loophole here so I am not worried about the hard cast.

2024-08-08 08:28 UTC, NunoAlexandre commented on app/src/hooks/useErc20Allowance.tsx
> +        }, 10000)
If we can fetch the allowance amount the user signed yes! That's what I was suggesting on Slack :) I'll look into that 👍🏻

2024-08-08 08:32 UTC, Victor-Salomon commented on app/src/components/Transfer.tsx
> +    erc20SpendAllowance !== undefined && erc20SpendAllowance < tokenAmount!.amount!
we should at least add the `&& sourceWallet?.isConnected` as currently if you disconnect it keeps handling the allowance. 

How about if a user asks for an allowance greater than his balance?

2024-08-08 08:41 UTC, Victor-Salomon commented on app/src/hooks/useErc20Allowance.tsx
> +      console.log('will set to undefined:', network)
can we remove the log?

2024-08-08 09:04 UTC, noahjoeris commented on app/src/hooks/useErc20Allowance.tsx
> +        !tokenAmount.token
Should we create a function `_basicChecks()`? Because they are very verbose and used twice in this hook. Just an idea.

2024-08-08 09:05 UTC, noahjoeris commented on app/src/hooks/useErc20Allowance.tsx
> +  const [approving, setApproving] = useState<boolean>(false)
Do we really need these two? Isn't loading enough?

2024-08-08 09:10 UTC, noahjoeris requested changes
Looks good 🚀  Left some comments

2024-08-08 09:17 UTC, NunoAlexandre commented on app/src/hooks/useErc20Allowance.tsx
> +  const [approving, setApproving] = useState<boolean>(false)
No. `loading` is regarding the fetching of the allowance; `approving` is about the act of signing the token spend approval. `loading` is actually not used at the moment

2024-08-08 09:39 UTC, NunoAlexandre commented on app/src/hooks/useErc20Allowance.tsx
> +        !tokenAmount.token
The problem with doing that is that the type system will no longer be aware of those checks, so we have to bang them to assert they are not null or undefined 👀  and the checks are slightly different across the two usages too...

2024-08-08 09:57 UTC, NunoAlexandre commented on app/src/components/Transfer.tsx
> +    erc20SpendAllowance !== undefined && erc20SpendAllowance < tokenAmount!.amount!
> we should just add the && sourceWallet?.isConnected as currently if you disconnect it keeps handling the allowance.


Good point! Let me look into it.


> How about if a user asks for an allowance greater than his balance?

It's fine as is, there's no problem with us displaying a propmpt to increase the allowance even in that scenario 👍

2024-08-08 10:11 UTC, NunoAlexandre commented on app/src/components/Transfer.tsx
> +    erc20SpendAllowance !== undefined && erc20SpendAllowance < tokenAmount!.amount!
@Victor-Salomon, Fixed 👍

2024-08-08 10:15 UTC, Victor-Salomon commented on app/src/hooks/useErc20Allowance.tsx
> +          .then(_ => fetchAllowance())
this is so clean now 🐢

2024-08-08 10:24 UTC, merged

2024-08-08 10:24 UTC, NunoAlexandre commented
@Victor-Salomon @noahjoeris thanks for your reviews 🤟